new path structure

diff --git a/install b/install
--- a/install
+++ b/install
@@ -106,8 +106,8 @@ if command -v 'mktemp' >'/dev/null' 2>&1; then
   z4h="$('command' 'mktemp' "$HOME"/.z4h.XXXXXXXXXX)"
   env="$('command' 'mktemp' "$HOME"/.env.zsh.XXXXXXXXXX)"
   brewinstall="$('command' 'mktemp' "$HOME"/brewinstall.sh.XXXXXXXXXX)"
-  brewfile="$('command' 'mktemp' "$HOME"/brewfile.install.XXXXXXXXXX)"
-  brewcask="$('command' 'mktemp' "$HOME"/brewcask.install.XXXXXXXXXX)"
+  brewfile="$('command' 'mktemp' "$HOME"/brewfile.XXXXXXXXXX)"
+  brewcask="$('command' 'mktemp' "$HOME"/brewcask.XXXXXXXXXX)"
   sdkman="$('command' 'mktemp' "$HOME"/sdkman.io.XXXXXXXXXX)"
 else
   zprofile="$HOME"/.zprofile.tmp."$$"
@@ -116,8 +116,8 @@ else
   z4h="$HOME"/.z4h.tmp."$$"
   env="$HOME"/.env.zsh.tmp."$$"
   brewinstall="$HOME"/brewinstall.sh."$$"
-  brewfile="$HOME"/brewfile.install."$$"
-  brewcask="$HOME"/brewcask.install."$$"
+  brewfile="$HOME"/brewfile."$$"
+  brewcask="$HOME"/brewcask."$$"
   sdkman="$HOME"/sdkman.io."$$"
 fi
 
@@ -174,14 +174,14 @@ if '[' "$macossetup" '=' '1' ']'; then
   >&2 'printf' '\033[31mInstallation of my preferred Homebrew formulas\033[0m \n'
   >&2 'printf' '\n'
 
-  if ! err="$($fetch "$brewfile" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewfile.install" 2>&1)"; then
+  if ! err="$($fetch "$brewfile" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewfile" 2>&1)"; then
     >&2 'printf' "%s\n" "$err"
-    >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewfile.install"
+    >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewfile"
   'command' 'rm' '-f' '--' "$brewfile" 2>'/dev/null'
     'exit' '1'
   else
     >&2 'printf' '\n'
-    >&2 'printf' '\033[33mbrew\033[0m: Start brew bundle --file from \033[1m%s\033[0m\n' "github.com/vmsimon/dotfiles/HEAD/install/brewcask.install"
+    >&2 'printf' '\033[33mbrew\033[0m: Start brew bundle --file from \033[1m%s\033[0m\n' "github.com/vmsimon/dotfiles/HEAD/brewfile"
     >&2 'printf' '\n'
     'command' 'brew' 'bundle' '--file' "$brewfile" 2>'/dev/null'
     'command' 'rm' '-f' '--' "$brewfile".lock.json
@@ -191,14 +191,14 @@ if '[' "$macossetup" '=' '1' ']'; then
   >&2 'printf' '\033[31mInstallation of my preferred Homebrew casks (macOS Application)\033[0m \n'
   >&2 'printf' '\n'
 
-  if ! err="$($fetch "$brewcask" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewcask.install" 2>&1)"; then
+  if ! err="$($fetch "$brewcask" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewcask" 2>&1)"; then
     >&2 'printf' "%s\n" "$err"
-    >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewcask.install"
+    >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/brewcask"
     'command' 'rm' '-f' '--' "$brewcask" 2>'/dev/null'
     'exit' '1'
   else
     >&2 'printf' '\n'
-    >&2 'printf' '\033[33mbrew\033[0m: Start brew bundle --file from \033[1m%s\033[0m\n' "github.com/vmsimon/dotfiles/HEAD/install/brewcask.install"
+    >&2 'printf' '\033[33mbrew\033[0m: Start brew bundle --file from \033[1m%s\033[0m\n' "github.com/vmsimon/dotfiles/HEAD/brewcask"
     >&2 'printf' '\n'
     'command' 'brew' 'bundle' '--file' "$brewcask" 2>'/dev/null'
     'command' 'rm' '-f' '--' "$brewcask".lock.json
@@ -249,6 +249,10 @@ if '[' "$macossetup" '=' '1' ']'; then
       >&2 'printf' '\n'
       'command' 'bash' '--' "$sdkman" 2>'/dev/null'
       'command' 'rm' '-f' '--' "$sdkman" 2>'/dev/null'
+      'command' 'source' '--' "~/.sdkman/bin/sdkman.init.sh" 2>'/dev/null'
+      'command' 'sdk' 'install' "java 8.0.382-tem" 2>'/dev/null'
+      'command' 'sdk' 'install' "java 11.0.20-tem" 2>'/dev/null'
+      'command' 'sdk' 'install' "java 17.0.8-tem" 2>'/dev/null'
     fi
   fi
 
