include zstyles from fzf-tab.zsh in .env.zsh

diff --git a/install b/install
--- a/install
+++ b/install
@@ -256,50 +256,45 @@ if '[' "$macossetup" '=' '1' ']'; then
       >&2 'printf' '\033[33mbrew\033[0m: Start SDKMan install from \033[1m%s\033[0m ...\n' "get.sdkman.io/"
       >&2 'printf' '\n'
       'command' 'bash' '--' "$sdkman" 2>'/dev/null'
+
+      >&2 'printf' '\n'
+      >&2 'printf' 'Do you want to install \033[32m Java Versions 8.0.382-tem, 11.0.20-tem, 17.0.8-tem with SDKMan.io \033[0m?\n'
+      >&2 'printf' '\n'
+      >&2 'printf' '  \033[1m(y)\033[0m  Yes.\n'
+      >&2 'printf' '  \033[1m(n)\033[0m  No.\n'
+      >&2 'printf' '\n'
+      while 'true'; do
+        >&2 'printf' '\033[1mChoice [yn]:\033[0m '
+        'read_choice'
+        case "$choice" in
+          'y'|'Y')
+            javainstall='1'
+            'break'
+          ;;
+          'n'|'N')
+            'break'
+          ;;
+          "$lf")
+          ;;
+          *)
+            >&2 'printf' '\033[33mz4h\033[0m: invalid choice: \033[31m%s\033[0m\n' "$choice"
+          ;;
+        esac
+      done
+      if '[' "$javainstall" '=' '1' ']'; then
+        >&2 'printf' '\n'
+        >&2 'printf' 'Installing \033[33mJava SDKs\033[0m...\n'
+        >&2 'printf' '\n'
+        if ! err="$($fetch "$sdkinstall" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/sdk.install" 2>&1)"; then
+          >&2 'printf' "%s\n" "$err"
+          >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/sdk.install
+          'command' 'rm' '-f' '--' "$sdkinstall" 2>'/dev/null'
+        else
+          'command' 'bash' '--' "$sdkinstall" 2>'/dev/null'
+        fi
+      fi
     fi
   fi
-
-  >&2 'printf' '\n'
-  >&2 'printf' '\033[31mInstallation of SDKMan (https://sdkman.io)\033[0m \n'
-  >&2 'printf' '\n'
-
-  >&2 'printf' '\n'
-  >&2 'printf' 'Do you want to install \033[32m Java Versions 8.0.382-tem, 11.0.20-tem, 17.0.8-tem with SDKMan.io \033[0m?\n'
-  >&2 'printf' '\n'
-  >&2 'printf' '  \033[1m(y)\033[0m  Yes.\n'
-  >&2 'printf' '  \033[1m(n)\033[0m  No.\n'
-  >&2 'printf' '\n'
-  while 'true'; do
-    >&2 'printf' '\033[1mChoice [yn]:\033[0m '
-    'read_choice'
-    case "$choice" in
-      'y'|'Y')
-        javainstall='1'
-        'break'
-      ;;
-      'n'|'N')
-        'break'
-      ;;
-      "$lf")
-      ;;
-      *)
-        >&2 'printf' '\033[33mz4h\033[0m: invalid choice: \033[31m%s\033[0m\n' "$choice"
-      ;;
-    esac
-  done
-  if '[' "$javainstall" '=' '1' ']'; then
-    >&2 'printf' '\n'
-    >&2 'printf' 'Installing \033[33mJava SDKs\033[0m...\n'
-    >&2 'printf' '\n'
-    if ! err="$($fetch "$sdkinstall" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/sdk.install" 2>&1)"; then
-      >&2 'printf' "%s\n" "$err"
-      >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/sdk.install
-      'command' 'rm' '-f' '--' "$sdkinstall" 2>'/dev/null'
-    else
-      'command' 'bash' '--' "$sdkinstall" 2>'/dev/null'
-    fi
-  fi
-
 fi
 
 >&2 'printf' '\n'
