inkl. personal settings

diff --git a/install b/install
--- a/install
+++ b/install
@@ -249,11 +249,46 @@ if '[' "$macossetup" '=' '1' ']'; then
       >&2 'printf' '\n'
       'command' 'bash' '--' "$sdkman" 2>'/dev/null'
       'command' 'rm' '-f' '--' "$sdkman" 2>'/dev/null'
-      'command' 'source' '--' "~/.sdkman/bin/sdkman.init.sh" 2>'/dev/null'
-      'command' 'sdk' 'install' "java 8.0.382-tem" 2>'/dev/null'
-      'command' 'sdk' 'install' "java 11.0.20-tem" 2>'/dev/null'
-      'command' 'sdk' 'install' "java 17.0.8-tem" 2>'/dev/null'
     fi
+  fi
+
+  >&2 'printf' '\n'
+  >&2 'printf' '\033[31mInstallation of SDKMan (https://sdkman.io)\033[0m \n'
+  >&2 'printf' '\n'
+
+  >&2 'printf' '\n'
+  >&2 'printf' 'Do you want to install \033[32m Java Versions 8.0.382-tem, 11.0.20-tem, 17.0.8-tem with SDKMan.io \033[0m?\n'
+  >&2 'printf' '\n'
+  >&2 'printf' '  \033[1m(y)\033[0m  Yes.\n'
+  >&2 'printf' '  \033[1m(n)\033[0m  No.\n'
+  >&2 'printf' '\n'
+  while 'true'; do
+    >&2 'printf' '\033[1mChoice [yn]:\033[0m '
+    'read_choice'
+    case "$choice" in
+      'y'|'Y')
+        javainstall='1'
+        'break'
+      ;;
+      'n'|'N')
+        'break'
+      ;;
+      "$lf")
+      ;;
+      *)
+        >&2 'printf' '\033[33mz4h\033[0m: invalid choice: \033[31m%s\033[0m\n' "$choice"
+      ;;
+    esac
+  done
+  if '[' "$javainstall" '=' '1' ']'; then
+    >&2 'printf' '\n'
+    >&2 'printf' 'Installing \033[33mJava SDKs\033[0m...\n'
+    >&2 'printf' '\n'
+
+    'command' 'source' "~/.sdkman/bin/sdkman-init.sh" 2>'/dev/null'
+    'command' 'sdk' 'install' "java 8.0.382-tem" 2>'/dev/null'
+    'command' 'sdk' 'install' "java 11.0.20-tem" 2>'/dev/null'
+    'command' 'sdk' 'install' "java 17.0.8-tem" 2>'/dev/null'
   fi
 
 fi
@@ -509,12 +544,28 @@ if '[' "$macossetup" '=' '1' ']'; then
     ;;
     *);;
   esac
+
+  >&2 'printf' '\033[33mz4h\033[0m: generating \033[4m~/.p10k.zsh\033[0m\n'
+  if ! err="$($fetch "~/.p10k.zsh" '--' https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/.p10k.zsh 2>&1)"; then
+    >&2 'printf' "%s\n" "$err"
+    >&2 'printf' '\033[33mz4h\033[0m: failed to download my personal \033[31m%s\033[0m\n' https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/.p10k.zsh
+  fi
+
   if '[' "$fzfgit" '=' '1' ']'; then
+    if ! err="$($fetch "~/.fzf-tab.zsh" '--' https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/.fzf-tab.zsh 2>&1)"; then
+      >&2 'printf' "%s\n" "$err"
+      >&2 'printf' '\033[33mz4h\033[0m: failed to download my personal \033[31m%s\033[0m\n' https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/.fzf-tab.zsh
+    else
+      'command' 'awk' "BEGIN {print \"# Source ~/.fzf-tab.sh.\"; print \"z4h source ~/fzf-tab.sh\"; print \"\"} 1" "$env" >"$env.bak"
+      'command' 'mv' '--' "$env.bak" "$env"
+    fi
+
     'command' 'awk' "/Install or update core components/ {print \"# Clone https://www.github.com/junegunn/fzf-git.sh.\"; print \"z4h install junegunn/fzf-git.sh || return\"; print \"\"} 1" "$zshrc" >"$zshrc.bak"
     'command' 'mv' '--' "$zshrc.bak" "$zshrc"
     'command' 'awk' "BEGIN {print \"# Source https://www.github.com/junegunn/fzf-git.sh.\"; print \"z4h source junegunn/fzf-git.sh/fzf-git.sh\"; print \"\"} 1" "$env" >"$env.bak"
     'command' 'mv' '--' "$env.bak" "$env"
   fi
+
   if '[' "$sdkman" '=' '1' ']'; then
     'command' 'awk' "END {print \"# Source https://sdkman.io.\"; print \"z4h source $\{HOME\}/.sdkman/bin/sdkman-init.sh\"; print \"\"} 1" "$env" >"$env.bak"
     'command' 'mv' '--' "$env.bak" "$env"
