modified p10k.zsh

diff --git a/install b/install
--- a/install
+++ b/install
@@ -74,10 +74,13 @@ brewinstall=''
 brewfile=''
 brewcask=''
 sdkman=''
+sdkinstall=''
+p10k=''
+fzftab=''
 
 cleanup() {
   'trap' '-' 'INT' 'TERM' 'EXIT'
-  'command' 'rm' '-f' '--' "$zprofile" "$zshenv" "$zshrc" "${zshrc:+$zshrc.bak}" "$z4h" "$env" "${env:+$env.bak}" "$brewinstall" "$brewfile" "$brewcask" "$sdkman" "$sdkinstall" "$p10k"
+  'command' 'rm' '-f' '--' "$zprofile" "$zshenv" "$zshrc" "${zshrc:+$zshrc.bak}" "$z4h" "$env" "${env:+$env.bak}" "$brewinstall" "$brewfile" "$brewcask" "$sdkman" "$sdkinstall" "$p10k" "$fzftab"
   'command' 'stty' "$saved_tty_settings"
 }
 
@@ -111,6 +114,7 @@ if command -v 'mktemp' >'/dev/null' 2>&1; then
   sdkman="$('command' 'mktemp' "$HOME"/sdkman.io.XXXXXXXXXX)"
   sdkinstall="$('command' 'mktemp' "$HOME"/sdkinstall.XXXXXXXXXX)"
   p10k="$('command' 'mktemp' "$HOME"/.p10k.zsh.XXXXXXXXXX)"
+  fzftab="$('command' 'mktemp' "$HOME"/.fzf-tab.zsh.XXXXXXXXXX)"
 else
   zprofile="$HOME"/.zprofile.tmp."$$"
   zshenv="$HOME"/.zshenv.tmp."$$"
@@ -123,6 +127,7 @@ else
   sdkman="$HOME"/sdkman.io."$$"
   sdkinstall="$HOME"/sdk.install."$$"
   p10k="$HOME"/.p10k.zsh."$$"
+  fzftab="$HOME"/.fzf-tab.zsh."$$"
 fi
 
 >&2 'printf' 'Greetings, Human!\n'
@@ -140,7 +145,6 @@ while 'true'; do
   case "$choice" in
     'y'|'Y')
       macossetup='1'
-      fzfgit='1' # atm no choice, just install and use it
       'break'
     ;;
     'n'|'N')
@@ -559,15 +563,26 @@ if '[' "$macossetup" '=' '1' ']'; then
     'command' 'mv' '--' "$p10k" ~/'.p10k.zsh'
   fi
 
-  if '[' "$fzfgit" '=' '1' ']'; then
-    'command' 'awk' "/Install or update core components/ {print \"# Clone https://www.github.com/junegunn/fzf-git.sh.\"; print \"z4h install junegunn/fzf-git.sh || return\"; print \"\"} 1" "$zshrc" >"$zshrc.bak"
-    'command' 'mv' '--' "$zshrc.bak" "$zshrc"
-    'command' 'awk' "BEGIN {print \"# Source https://www.github.com/junegunn/fzf-git.sh.\"; print \"z4h source junegunn/fzf-git.sh/fzf-git.sh\"; print \"\"} 1" "$env" >"$env.bak"
-    'command' 'mv' '--' "$env.bak" "$env"
+  'command' 'awk' "/Install or update core components/ {print \"# Clone https://www.github.com/junegunn/fzf-git.sh.\"; print \"z4h install junegunn/fzf-git.sh || return\"; print \"\"} 1" "$zshrc" >"$zshrc.bak"
+  'command' 'mv' '--' "$zshrc.bak" "$zshrc"
+  'command' 'awk' "BEGIN {print \"# Source https://www.github.com/junegunn/fzf-git.sh.\"; print \"z4h source junegunn/fzf-git.sh/fzf-git.sh\"; print \"\"} 1" "$env" >"$env.bak"
+  'command' 'mv' '--' "$env.bak" "$env"
+
+  >&2 'printf' '\033[33mz4h\033[0m: including \033[4m~/.fzf-tab.zsh\033[0m\n in \033[4m~/.env.zsh\033[0m\n'
+  if ! err="$($fetch "$fzftab" '--' https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/.fzf-tab.zsh 2>&1)"; then
+    >&2 'printf' "%s\n" "$err"
+    >&2 'printf' '\033[33mz4h\033[0m: failed to download my personal \033[31m%s\033[0m\n' https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/.fzf-tab.zsh
+    'command' 'rm' '-f' '--' "$fzftab"
+  else
+    'command' 'cat' "$fzftab" '>>' "$env"
+    'command' 'rm' '-f' '--' "$fzftab"
   fi
 
+  'command' 'awk' "END {print \"# # disable sort when completing git checkout\"; print \"z4h source $\{HOME\}/.sdkman/bin/sdkman-init.sh\"; print \"\"} 1" "$env" >"$env.bak"
+  'command' 'mv' '--' "$env.bak" "$env"
+
   if '[' "$sdkman" '=' '1' ']'; then
-    'command' 'awk' "END {print \"# Source https://sdkman.io.\"; print \"z4h source $\{HOME\}/.sdkman/bin/sdkman-init.sh\"; print \"\"} 1" "$env" >"$env.bak"
+    'command' 'awk' "END {print \"# Source https://sdkman.io.\"; print \"zstyle ':completion:*:git-checkout:*' sort false\"; print \"\"} 1" "$env" >"$env.bak"
     'command' 'mv' '--' "$env.bak" "$env"
   fi
 fi
