new path structure

diff --git a/install b/install
--- a/install
+++ b/install
@@ -174,9 +174,9 @@ if '[' "$macossetup" '=' '1' ']'; then
   >&2 'printf' '\033[31mInstallation of my preferred Homebrew formulas\033[0m \n'
   >&2 'printf' '\n'
 
-  if ! err="$($fetch "$brewfile" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewfile" 2>&1)"; then
+  if ! err="$($fetch "$brewfile" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/brewfile" 2>&1)"; then
     >&2 'printf' "%s\n" "$err"
-    >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewfile"
+    >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/brewfile"
   'command' 'rm' '-f' '--' "$brewfile" 2>'/dev/null'
     'exit' '1'
   else
@@ -191,7 +191,7 @@ if '[' "$macossetup" '=' '1' ']'; then
   >&2 'printf' '\033[31mInstallation of my preferred Homebrew casks (macOS Application)\033[0m \n'
   >&2 'printf' '\n'
 
-  if ! err="$($fetch "$brewcask" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewcask" 2>&1)"; then
+  if ! err="$($fetch "$brewcask" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/brewcask" 2>&1)"; then
     >&2 'printf' "%s\n" "$err"
     >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/brewcask"
     'command' 'rm' '-f' '--' "$brewcask" 2>'/dev/null'
