Test integration zsh4humans

diff --git a/new_install b/new_install
--- a/new_install
+++ b/new_install
@@ -233,7 +233,35 @@ while 'true'; do
       'break'
     ;;
     'n'|'N')
-      fzfgit='0'
+      'break'
+    ;;
+    'q'|'Q')
+      'exit' '1'
+    ;;
+    "$lf")
+    ;;
+    *)
+      >&2 'printf' '\033[33mz4h\033[0m: invalid choice: \033[31m%s\033[0m\n' "$choice"
+    ;;
+  esac
+done
+
+>&2 'printf' '\n'
+>&2 'printf' 'Do you want to setup \033[32m macOS Environment\033[0m?\n'
+>&2 'printf' '\n'
+>&2 'printf' '  \033[1m(y)\033[0m  Yes.\n'
+>&2 'printf' '  \033[1m(n)\033[0m  No.\n'
+>&2 'printf' '  \033[1m(q)\033[0m  Quit and do nothing.\n'
+>&2 'printf' '\n'
+while 'true'; do
+  >&2 'printf' '\033[1mChoice [ynq]:\033[0m '
+  'read_choice'
+  case "$choice" in
+    'y'|'Y')
+      macossetup='1'
+      'break'
+    ;;
+    'n'|'N')
       'break'
     ;;
     'q'|'Q')
@@ -371,6 +399,11 @@ fi
 if '[' '-r' '/proc/version' ']' && 'command' 'grep' '-q' '[Mm]icrosoft' '/proc/version' 2>'/dev/null'; then
   'command' 'awk' "/Clone additional Git repositories from GitHub/ {print \"# Start ssh-agent if it's not running yet.\"; print \"zstyle ':z4h:ssh-agent:' start yes\"; print \"\"} 1" "$zshrc" >"$zshrc.bak"
   'command' 'mv' '--' "$zshrc.bak" "$zshrc"
+fi
+
+if '[' "macossetup" '=' '1' ']'; then
+        url=https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
+        'command' '/bin/bash -c' "$(curl -fsSL ${url})"
 fi
 
 Z4H="${XDG_CACHE_HOME:-$HOME/.cache}/zsh4humans/v5"
