Test integration zsh4humans

diff --git a/new_install b/new_install
--- a/new_install
+++ b/new_install
@@ -151,13 +151,13 @@ if '[' "$macossetup" '=' '1' ']'; then
   >&2 'printf' '\033[31mInstallation of Homebrew\033[0m \n'
   >&2 'printf' '\n'
 
-  if ! err="$($fetch "$brewinstall" '--' "https://raw.githubusercontent.com/Homebrew/install/master/install.sh" 2>&1)"; then
+  if ! err="$($fetch "$brewinstall" '--' "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh" 2>&1)"; then
     >&2 'printf' "%s\n" "$err"
-    >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/Homebrew/install/master/install.sh"
+    >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
     'command' 'rm' '-f' '--' "$brewinstall" 2>'/dev/null'
     'exit' '1'
   else
-    >&2 'printf' '\033[33mbrew\033[0m: Start Homebrew install from \033[1m%s\033[0m ...\n' "github.com/Homebrew/install/master/install.sh"
+    >&2 'printf' '\033[33mbrew\033[0m: Start Homebrew install from \033[1m%s\033[0m ...\n' "github.com/Homebrew/install/HEAD/install.sh"
     >&2 'printf' '\n'
     'command' 'bash' '--' "$brewinstall" 2>'/dev/null'
   fi
@@ -168,12 +168,12 @@ if '[' "$macossetup" '=' '1' ']'; then
 
   if ! err="$($fetch "$brewfile" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewfile.install" 2>&1)"; then
     >&2 'printf' "%s\n" "$err"
-    >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/vmsimon/dotfiles/master/install/brewfile.install"
+    >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewfile.install"
   'command' 'rm' '-f' '--' "$brewfile" 2>'/dev/null'
     'exit' '1'
   else
     >&2 'printf' '\n'
-    >&2 'printf' '\033[33mbrew\033[0m: Start brew bundle --file from \033[1m%s\033[0m\n' "github.com/vmsimon/dotfiles/master/install/brewcask.install"
+    >&2 'printf' '\033[33mbrew\033[0m: Start brew bundle --file from \033[1m%s\033[0m\n' "github.com/vmsimon/dotfiles/HEAD/install/brewcask.install"
     >&2 'printf' '\n'
     'command' 'brew' 'bundle' '--file' "$brewfile" 2>'/dev/null'
   fi
@@ -182,14 +182,14 @@ if '[' "$macossetup" '=' '1' ']'; then
   >&2 'printf' '\033[31mInstallation of my preferred Homebrew Casks (macOS Application)\033[0m \n'
   >&2 'printf' '\n'
 
-  if ! err="$($fetch "$brewcask" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/master/install/brewcask.install" 2>&1)"; then
+  if ! err="$($fetch "$brewcask" '--' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewcask.install" 2>&1)"; then
     >&2 'printf' "%s\n" "$err"
-    >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/vmsimon/dotfiles/master/install/brewcask.install"
+    >&2 'printf' '\033[33mz4h\033[0m: failed to download \033[31m%s\033[0m\n' "https://raw.githubusercontent.com/vmsimon/dotfiles/HEAD/install/brewcask.install"
     'command' 'rm' '-f' '--' "$brewcask" 2>'/dev/null'
     'exit' '1'
   else
     >&2 'printf' '\n'
-    >&2 'printf' '\033[33mbrew\033[0m: Start brew bundle --file from \033[1m%s\033[0m\n' "github.com/vmsimon/dotfiles/master/install/brewcask.install"
+    >&2 'printf' '\033[33mbrew\033[0m: Start brew bundle --file from \033[1m%s\033[0m\n' "github.com/vmsimon/dotfiles/HEAD/install/brewcask.install"
     >&2 'printf' '\n'
     'command' 'brew' 'bundle' '--file' "$brewcask" 2>'/dev/null'
   fi
